#!/usr/bin/env python3
"""Emit LaTeX tables of measured values against analytical expectations.

Every number is computed at run time from the same synthetic fixtures the test
suite uses. Nothing is transcribed by hand, so the documents cannot drift out
of agreement with the code.

    python docs/make_tables.py
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests"))

from conftest import (  # noqa: E402  # type: ignore[import-not-found]
    ANNULUS_EXACT_VOLUME_MM3,
    ANNULUS_HEIGHT_MM,
    ANNULUS_INNER_MM,
    ANNULUS_OUTER_MM,
    CUBE_AREA_MM2,
    CUBE_MEAN_DIHEDRAL_DEG,
    CUBE_VOLUME_MM3,
    build_annulus,
    build_box,
    build_sphere,
)
from relief_forge import signed_volume, surface_area, weld  # noqa: E402
from relief_forge.measurements import material_masses, mean_dihedral_angle  # noqa: E402
from relief_forge.symmetry import symmetrize  # noqa: E402
from relief_forge.topology import analyse_topology  # noqa: E402

OUTPUT = ROOT / "docs" / "generated"

HEADER = "% Generated by docs/make_tables.py. Do not edit by hand.\n"


def _escape(text: str) -> str:
    return text.replace("_", "\\_")


def measurement_rows() -> list[tuple[str, str, float, float, float]]:
    """Return (quantity, unit, expected, measured, tolerance) tuples."""
    cube = build_box()
    annulus = build_annulus()
    sphere = build_sphere(radius=8.0, subdivisions=5, offset=(0.0, 0.0, 0.0))
    welded_cube = weld(cube)

    annulus_area = (
        2.0 * math.pi * (ANNULUS_OUTER_MM + ANNULUS_INNER_MM) * ANNULUS_HEIGHT_MM
        + 2.0 * math.pi * (ANNULUS_OUTER_MM**2 - ANNULUS_INNER_MM**2)
    )
    sphere_volume = 4.0 / 3.0 * math.pi * 8.0**3

    cap_height = 8.0 - 2.0
    cap_volume = 2.0 * math.pi * cap_height**2 * (3.0 * 8.0 - cap_height) / 3.0
    symmetrized = symmetrize(
        build_sphere(radius=8.0, subdivisions=5, offset=(2.0, 0.0, 0.0)), "x", 0.0
    )

    box = build_box(low=(-10, -6, 0), high=(5, 6, 4))
    box_sym = symmetrize(box, "x", 0.0)

    return [
        ("Cube volume", "mm$^3$", CUBE_VOLUME_MM3, signed_volume(cube), 1e-9),
        ("Cube surface area", "mm$^2$", CUBE_AREA_MM2, surface_area(cube), 1e-9),
        (
            "Cube mean dihedral angle",
            "deg",
            CUBE_MEAN_DIHEDRAL_DEG,
            mean_dihedral_angle(welded_cube.vertices, welded_cube.faces),
            1e-9,
        ),
        (
            "Cube cast mass, silver 925",
            "g",
            10.36,
            material_masses(CUBE_VOLUME_MM3)["silver_925"],
            1e-9,
        ),
        (
            "Annulus volume",
            "mm$^3$",
            ANNULUS_EXACT_VOLUME_MM3,
            signed_volume(annulus),
            3e-3,
        ),
        ("Annulus surface area", "mm$^2$", annulus_area, surface_area(annulus), 3e-3),
        ("Sphere volume", "mm$^3$", sphere_volume, signed_volume(sphere), 1e-2),
        (
            "Symmetrized sphere volume (cap formula)",
            "mm$^3$",
            cap_volume,
            signed_volume(symmetrized),
            2e-2,
        ),
        (
            "Symmetrized box volume",
            "mm$^3$",
            20.0 * 12.0 * 4.0,
            signed_volume(box_sym),
            1e-9,
        ),
    ]


def write_measurement_table() -> Path:
    rows = measurement_rows()
    lines = [
        HEADER.rstrip(),
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "Quantity & Unit & Expected & Measured & Rel.\\ error & Tolerance \\\\",
        "\\midrule",
    ]
    for name, unit, expected, measured, tolerance in rows:
        error = abs(measured - expected) / abs(expected)
        # Thousands separators are applied to the numeric fields only; applying
        # them to the whole row would also rewrite commas inside labels.
        expected_s = f"{expected:,.4f}".replace(",", "\\,")
        measured_s = f"{measured:,.4f}".replace(",", "\\,")
        lines.append(
            f"{_escape(name)} & {unit} & {expected_s} & {measured_s} & "
            f"\\num{{{error:.2e}}} & \\num{{{tolerance:.0e}}} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]

    path = OUTPUT / "measurement_table.tex"
    path.write_text("\n".join(lines))
    return path


def defect_rows() -> list[tuple[str, str, str]]:
    """Return (fixture, injected defect, detected classification) tuples."""
    cube = build_box()

    reversed_tri = cube.copy()
    reversed_tri[-1] = reversed_tri[-1][::-1]

    import numpy as np

    cases = [
        ("Closed cube", "none", cube),
        ("Cube, one face removed", "open surface", cube[:-2]),
        ("Cube, one triangle reversed", "winding", reversed_tri),
        (
            "Cube with attached flap",
            "non-manifold",
            np.concatenate([cube, build_box(low=(0, 0, 10), high=(10, 10, 20))[:2]]),
        ),
        (
            "Two separated cubes",
            "disconnected",
            np.concatenate([cube, build_box(low=(50, 0, 0), high=(60, 10, 10))]),
        ),
        ("Annulus (genus one)", "none", build_annulus()),
        ("Inverted cube", "orientation", cube[:, ::-1, :].copy()),
    ]

    labels = {
        "boundary_edges": "boundary",
        "nonmanifold_edges": "non-manifold",
        "inconsistent_edges": "winding",
        "degenerate_edges": "degenerate",
    }

    rows = []
    for name, injected, mesh in cases:
        welded = weld(mesh)
        report = analyse_topology(welded.faces, len(welded.vertices))
        found = [f"{count} {labels[key]}" for key, count in report.defects().items()]
        if report.components > 1:
            found.append(f"{report.components} components")
        if signed_volume(mesh) <= 0:
            found.append("negative volume")
        rows.append((name, injected, ", ".join(found) or "none"))
    return rows


def write_defect_table() -> Path:
    lines = [
        HEADER.rstrip(),
        "\\begin{tabular}{lll}",
        "\\toprule",
        "Fixture & Injected defect & Detected \\\\",
        "\\midrule",
    ]
    for name, injected, detected in defect_rows():
        lines.append(f"{_escape(name)} & {injected} & {detected} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]

    path = OUTPUT / "defect_table.tex"
    path.write_text("\n".join(lines))
    return path


def main() -> int:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for path in (write_measurement_table(), write_defect_table()):
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
